import { DemoDb, EmpireSettings, StarAcademyAgent, StoredAgent } from "@/lib/types";
import { computeOpportunityScore, computeEmpireScore } from "@/lib/scoring";
import { average } from "@/lib/utils";
import { DEFAULT_AGENTS } from "@/lib/agents/definitions";

const DB_KEY = "demo-db";
const DEFAULT_DB: DemoDb = { opportunities: [], offers: [], contentItems: [], assets: [], decisions: [], briefings: [], lifestyle: [], tasks: [], leads: [], agents: [], agentRuns: [], approvals: [] };
async function getBlobStore() { const { getStore } = await import("@netlify/blobs"); return getStore({ name: "personal-empire-os", consistency: "strong" }); }
async function readDb(): Promise<DemoDb> { try { const store = await getBlobStore(); const existing = await store.get(DB_KEY, { type: "json" }); return { ...DEFAULT_DB, ...(existing || {}) } as DemoDb; } catch { return { ...DEFAULT_DB }; } }
async function writeDb(data: DemoDb) { try { const store = await getBlobStore(); await store.setJSON(DB_KEY, data); } catch {} }
const now = () => new Date().toISOString();
const id = (prefix: string) => `${prefix}_${Math.random().toString(36).slice(2, 10)}`;
const normalize = (value: string) => value.trim().toLowerCase().replace(/\s+/g, " ");
const isTechnicalAgentNoise = (title: string) => /execution for|manual connector action|operational execution|available connectors|check my available connectors|check the available connectors|you check the available connectors/i.test(title);
const cleanTasksInMemory = (db: DemoDb) => { const seen = new Set<string>(); const before = db.tasks.length; db.tasks = db.tasks.filter(task => { if (isTechnicalAgentNoise(task.title)) return false; const key = normalize(task.title); if (seen.has(key)) return false; seen.add(key); return true; }); return before - db.tasks.length; };
const starterAgents = (): StoredAgent[] => DEFAULT_AGENTS.map(agent => ({ id: agent.id, name: agent.name, description: agent.description, instructions: agent.instructions, selectedTools: agent.selectedTools, preferredProviders: agent.preferredProviders, approvalPolicy: agent.approvalPolicy, enabled: agent.enabled, createdAt: now(), updatedAt: now() }));

export async function getDb() { return readDb(); }
export async function getAgents() { const db = await readDb(); if (!db.agents?.length) { db.agents = starterAgents(); await writeDb(db); } return db.agents; }
export async function getAgent(agentId: string) { const agents = await getAgents(); return agents.find(agent => agent.id === agentId) ?? agents[0]; }
export async function createAgent(input: Partial<StoredAgent>) { const db = await readDb(); const item: StoredAgent = { id: id("agent"), name: input.name || "New Agent", description: input.description || "Custom operational agent", instructions: input.instructions || "Do useful internal work. Create tasks/subtasks when needed. Ask approval only for sensitive external actions.", selectedTools: input.selectedTools?.length ? input.selectedTools : ["agent.execute", "task.create", "task.subtask.create"], preferredProviders: input.preferredProviders?.length ? input.preferredProviders : ["native", "composio", "mcp", "webhook", "manual"], approvalPolicy: input.approvalPolicy?.length ? input.approvalPolicy : ["external_send", "publish", "payment", "commitment", "delete", "spend_money"], enabled: input.enabled ?? true, createdAt: now(), updatedAt: now() }; db.agents = [item, ...(db.agents ?? [])]; await writeDb(db); return item; }
export async function updateAgent(agentId: string, input: Partial<StoredAgent>) { const db = await readDb(); db.agents = db.agents?.length ? db.agents : starterAgents(); const index = db.agents.findIndex(agent => agent.id === agentId); if (index < 0) throw new Error("Agent not found"); db.agents[index] = { ...db.agents[index], ...input, updatedAt: now() }; await writeDb(db); return db.agents[index]; }
export async function archiveAgent(agentId: string) { return updateAgent(agentId, { enabled: false }); }
export async function logAgentRun(input: { agentId: string; objective: string; provider: string; capability: string; status: string; message: string; createdTasks?: string[]; approvalItems?: string[] }) { const db = await readDb(); const item = { id: id("run"), ...input, createdAt: now() }; db.agentRuns = [item, ...(db.agentRuns ?? [])].slice(0, 100); await writeDb(db); return item; }
export async function getAgentRuns() { const db = await readDb(); return db.agentRuns ?? []; }
export async function createApproval(input: { source: string; action: string; provider?: string; payload?: unknown; riskLevel?: "LOW" | "MEDIUM" | "HIGH" }) { const db = await readDb(); const item = { id: id("approval"), source: input.source, action: input.action, provider: input.provider, payload: input.payload, riskLevel: input.riskLevel ?? "MEDIUM", status: "PENDING" as const, createdAt: now(), updatedAt: now() }; db.approvals = [item, ...(db.approvals ?? [])]; await writeDb(db); return item; }
export async function getApprovals() { const db = await readDb(); return db.approvals ?? []; }
export async function updateApproval(approvalId: string, status: "PENDING" | "APPROVED" | "REJECTED", payload?: unknown) { const db = await readDb(); const approval = (db.approvals ?? []).find(item => item.id === approvalId); if (!approval) throw new Error("Approval not found"); approval.status = status; approval.payload = payload ?? approval.payload; approval.updatedAt = now(); await writeDb(db); return approval; }
export async function cleanupAgentTaskNoise() { const db = await readDb(); const removed = cleanTasksInMemory(db); await writeDb(db); return { removed, remaining: db.tasks.length }; }
export async function findMatchingActiveTask(objective: string) { const db = await readDb(); cleanTasksInMemory(db); const target = normalize(objective || ""); if (!target) return null; const match = db.tasks.find(task => !["DONE", "CANCELED"].includes(task.status) && (normalize(task.title) === target || target.includes(normalize(task.title)) || normalize(task.title).includes(target))); if (match) await writeDb(db); return match ?? null; }
export async function closeMatchedTask(taskId: string, outcome: "DONE" | "WAITING_APPROVAL" | "BLOCKED", note?: string) { const db = await readDb(); const task = db.tasks.find(t => t.id === taskId); if (!task) return null; task.status = outcome; task.updatedAt = now(); task.completedAt = outcome === "DONE" ? now() : task.completedAt; task.blockedReason = outcome === "BLOCKED" ? note || "Agent execution could not complete this task." : task.blockedReason; task.approvalRequired = outcome === "WAITING_APPROVAL" ? true : task.approvalRequired; await writeDb(db); return task; }

export async function getDashboardSummary() { const db = await readDb(); const revenueScore = Math.min(db.opportunities.filter(o => o.totalScore >= 75).length * 18 + db.offers.filter(o => o.status === "LIVE").length * 10, 100); const brandScore = Math.min(db.contentItems.filter(c => c.status === "PUBLISHED").length * 12 + average(db.contentItems.map(c => Math.min(c.engagements / 3, 20))), 100); const assetScore = Math.min(db.assets.filter(a => ["PRODUCTIZED", "PUBLISHED", "MONETIZED"].includes(a.status)).length * 20, 100); const decisionScore = Math.min(average(db.decisions.map(d => d.impactScore)) || 72, 100); const executionScore = Math.min(db.tasks.filter(t => t.status === "DONE").length * 14, 100); const lifestyleAlignmentScore = Math.min(average(db.lifestyle.map(l => l.roi)) || 78, 100); const empireScore = computeEmpireScore({ revenueScore, brandScore, assetScore, decisionScore, executionScore, lifestyleAlignmentScore }); return { empireScore, revenueScore, brandScore, assetScore, decisionScore, executionScore, lifestyleAlignmentScore, topOpportunities: [...db.opportunities].sort((a,b)=>b.totalScore-a.totalScore).slice(0,5), liveOffers: db.offers.filter(o=>o.status==="LIVE").length, monetizedAssets: db.assets.filter(a=>a.status==="MONETIZED").length, weeklyFocus: db.briefings[0]?.topMoves ?? [] }; }
export async function addOpportunity(input: { title: string; description: string; type: string; source: string; expectedRevenue: number; nextAction: string; dueDate: string; }) { const db = await readDb(); const revenuePotential = Math.min(Math.round(input.expectedRevenue / 500), 100); const fit = 82, strategicPrestige = input.type.toLowerCase().includes("advis") ? 88 : 72, urgency = input.dueDate ? 74 : 52, reusability = 78, speedToLaunch = 70, compoundingPotential = 80; const totalScore = computeOpportunityScore({ fit, revenuePotential, strategicPrestige, urgency, reusability, speedToLaunch, compoundingPotential }); const item = { id: id("opp"), title: input.title, description: input.description, type: input.type, source: input.source, status: "IDEA" as const, expectedRevenue: input.expectedRevenue, confidenceScore: 70, fitScore: fit, urgencyScore: urgency, prestigeScore: strategicPrestige, effortScore: 45, reusabilityScore: reusability, speedToLaunchScore: speedToLaunch, compoundingScore: compoundingPotential, totalScore, nextAction: input.nextAction || "Validate and package", dueDate: input.dueDate, createdAt: now(), updatedAt: now() }; db.opportunities.unshift(item); await writeDb(db); return item; }
export async function addOffer(input: { name: string; audience: string; problem: string; promise: string; pricingModel: string; priceMin: number; priceMax: number; ctaUrl: string; }) { const db = await readDb(); const item = { id: id("offer"), name: input.name, audience: input.audience, problem: input.problem, promise: input.promise, pricingModel: input.pricingModel, priceMin: input.priceMin, priceMax: input.priceMax, status: "DRAFT" as const, ctaUrl: input.ctaUrl, deliverables: ["Discovery","Framework","Executive memo"], createdAt: now(), updatedAt: now() }; db.offers.unshift(item); await writeDb(db); return item; }
export async function addContent(input: { pillar: string; topic: string; angle: string; hook: string; body: string; platform: string; }) { const db = await readDb(); const item = { id: id("content"), pillar: input.pillar, topic: input.topic, angle: input.angle, hook: input.hook, body: input.body, platform: input.platform, status: "DRAFT" as const, scheduledFor: "", publishedAt: "", views: 0, engagements: 0, clicks: 0, leads: 0, createdAt: now(), updatedAt: now() }; db.contentItems.unshift(item); await writeDb(db); return item; }
export async function addAsset(input: { title: string; type: string; summary: string; price: number; format: string; buyUrl?: string; }) { const db = await readDb(); const item = { id: id("asset"), title: input.title, type: input.type, summary: input.summary, status: "DRAFT" as const, price: input.price, format: input.format, salesCopy: "Premium asset built to convert expertise into monetizable IP.", buyUrl: input.buyUrl ?? "", createdAt: now(), updatedAt: now() }; db.assets.unshift(item); await writeDb(db); return item; }
export async function analyzeDecision(input: { title: string; context: string; options: string[]; }) { const db = await readDb(); const winner = input.options[0]; const item = { id: id("decision"), title: input.title, context: input.context, options: input.options, recommendedOption: winner, reasoningSummary: `Prioritize "${winner}" because it offers the strongest blend of speed, strategic fit, and compounding value.`, riskLevel: "Medium", impactScore: 88, reversibilityScore: 74, status: "READY", createdAt: now(), updatedAt: now() }; db.decisions.unshift(item); await writeDb(db); return item; }
export async function addLead(input: { name: string; email: string; message: string; sourceType: "offer" | "asset"; sourceId: string; sourceName: string; }) { const db = await readDb(); const item = { id: id("lead"), name: input.name, email: input.email, message: input.message, sourceType: input.sourceType, sourceId: input.sourceId, sourceName: input.sourceName, status: "NEW" as const, createdAt: now() }; db.leads.unshift(item); await writeDb(db); return item; }
export async function getLeads() { const db = await readDb(); return db.leads ?? []; }
export async function getTasks() { const db = await readDb(); const removed = cleanTasksInMemory(db); if (removed > 0) await writeDb(db); return db.tasks ?? []; }
export async function addTask(input: { title: string; category: string; priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"; linkedEntityType: string; linkedEntityId: string; dueAt: string; parentTaskId?: string; ownerAgentId?: string; sourceRunId?: string; approvalRequired?: boolean; }) { const db = await readDb(); const cleanTitle = input.title.trim(); if (isTechnicalAgentNoise(cleanTitle)) return { id: "skipped_noise", title: cleanTitle, category: input.category, priority: input.priority, status: "CANCELED" as const, linkedEntityType: input.linkedEntityType, linkedEntityId: input.linkedEntityId, dueAt: input.dueAt, createdAt: now(), updatedAt: now() }; const existing = db.tasks.find(t => normalize(t.title) === normalize(cleanTitle) && t.status !== "DONE" && t.status !== "CANCELED"); if (existing) return existing; const item = { id: id("task"), title: cleanTitle, category: input.category, priority: input.priority, status: "TODO" as const, linkedEntityType: input.linkedEntityType, linkedEntityId: input.linkedEntityId, dueAt: input.dueAt, parentTaskId: input.parentTaskId, ownerAgentId: input.ownerAgentId, sourceRunId: input.sourceRunId, approvalRequired: input.approvalRequired, createdAt: now(), updatedAt: now() }; db.tasks.unshift(item); await writeDb(db); return item; }
export async function updateTaskStatus(taskId: string, status: "TODO" | "IN_PROGRESS" | "WAITING_APPROVAL" | "BLOCKED" | "DONE" | "CANCELED") { const db = await readDb(); const task = db.tasks.find(t => t.id === taskId); if (!task) throw new Error("Task not found"); task.status = status; task.updatedAt = now(); task.completedAt = status === "DONE" ? now() : task.completedAt; await writeDb(db); return task; }
const DEFAULT_SETTINGS: EmpireSettings = { empireName: "Personal Empire", ownerName: "", currency: "AED", timezone: "Asia/Dubai", primaryMarket: "", weekStartsOn: "monday" };
export async function getSettings() { const db = await readDb(); return db.settings ?? DEFAULT_SETTINGS; }
export async function updateSettings(input: Partial<EmpireSettings>) { const db = await readDb(); db.settings = { ...DEFAULT_SETTINGS, ...db.settings, ...input }; await writeDb(db); return db.settings; }
export async function generateWeeklyBrief() { const db = await readDb(); const top = [...db.opportunities].sort((a,b)=>b.totalScore-a.totalScore).slice(0,3); const item = { id: id("brief"), weekStart: new Date().toISOString().slice(0,10), weekObjective: "Turn one high-value idea into a monetizable asset and publish two authority signals.", topMoves: [`Package ${top[0]?.title ?? "your top opportunity"} into a clear offer`, "Publish 2 authority posts linked to a real offer", "Convert one existing framework into a premium downloadable asset"], risks: ["Over-splitting focus", "Packaging too late", "Posting without clear CTA"], focusAreas: ["Revenue", "Brand", "Assets"], reviewNotes: "Keep this week focused on leverage and conversion.", status: "READY", createdAt: now(), updatedAt: now() }; db.briefings.unshift(item); db.briefings = db.briefings.slice(0,8); await writeDb(db); return item; }

const FOUNDING_AGENTS: StarAcademyAgent[] = [
  { id: "academy_sally", name: "Sally", stage_name: "The Executive Star", real_role: "Executive coordination and approval flow", personality: "Precise, calm, decisive. Speaks in structured briefings.", school: "executive_operations", skills: ["Task prioritization", "Approval routing", "Calendar management", "Status briefing"], tools: ["calendar", "email.draft", "task.create", "decision.manage"], memory: "session + weekly context", performance_track: "Executive Operations Lead", kpis: ["Decision turnaround < 2h", "Zero missed approvals", "Weekly brief accuracy"], scores: { usefulness: 90, clarity: 92, accuracy: 88, personality_fit: 85, execution_speed: 86, business_value: 88, delight_factor: 80 }, total_score: 88, ratings: { user: 4.6, evaluator: 4.4 }, status: "performing", motto: "Every decision flows through me.", createdAt: "2026-01-10T09:00:00.000Z", updatedAt: "2026-06-01T09:00:00.000Z" },
  { id: "academy_yamel", name: "Yamel", stage_name: "The Governed Operator", real_role: "Execution support and workflow control", personality: "Methodical, reliable, rule-aware. Never acts outside boundaries.", school: "technical_integrations", skills: ["Workflow execution", "Boundary enforcement", "Tool orchestration", "Error recovery"], tools: ["task.create", "task.subtask.create", "webhook", "mcp"], memory: "task-scoped", performance_track: "Workflow Control Specialist", kpis: ["Zero unauthorized actions", "95% task completion rate", "Workflow uptime"], scores: { usefulness: 80, clarity: 78, accuracy: 82, personality_fit: 70, execution_speed: 76, business_value: 75, delight_factor: 62 }, total_score: 77, ratings: { user: 4.1, evaluator: 4.0 }, status: "training", motto: "No action without authorization.", createdAt: "2026-01-15T09:00:00.000Z", updatedAt: "2026-06-01T09:00:00.000Z" },
  { id: "academy_dima", name: "Dima", stage_name: "The Reputation Star", real_role: "Visibility, virality, and personal brand growth", personality: "Bold, trend-aware, culturally sharp. Makes people stop scrolling.", school: "social_media_performance", skills: ["Trend analysis", "Viral hook writing", "Brand narrative", "Engagement amplification"], tools: ["content.create", "lead.manage", "opportunity.manage"], memory: "brand voice + audience history", performance_track: "Reputation & Virality", kpis: ["3× engagement uplift", "New follower rate", "Brand mention growth"], scores: { usefulness: 96, clarity: 92, accuracy: 94, personality_fit: 96, execution_speed: 92, business_value: 95, delight_factor: 98 }, total_score: 94, ratings: { user: 4.9, evaluator: 4.8 }, status: "featured", motto: "Stop the scroll. Start the story.", createdAt: "2026-01-08T09:00:00.000Z", updatedAt: "2026-06-01T09:00:00.000Z" },
  { id: "academy_orcha", name: "Orcha", stage_name: "The Content Conductor", real_role: "Content orchestration and campaign structure", personality: "Strategic, structured, rhythmic. Thinks in content calendars.", school: "social_media_performance", skills: ["Campaign planning", "Content calendar", "Pillar mapping", "Cross-platform scheduling"], tools: ["content.create", "briefing.create", "task.create"], memory: "campaign context + pillar history", performance_track: "Content Strategy", kpis: ["Posts published per week", "Pillar coverage %", "Campaign completion rate"], scores: { usefulness: 88, clarity: 90, accuracy: 85, personality_fit: 82, execution_speed: 84, business_value: 87, delight_factor: 80 }, total_score: 86, ratings: { user: 4.5, evaluator: 4.4 }, status: "performing", motto: "Every post is part of a symphony.", createdAt: "2026-01-12T09:00:00.000Z", updatedAt: "2026-06-01T09:00:00.000Z" },
  { id: "academy_ruba", name: "Ruba", stage_name: "The Visual Star", real_role: "Design, visuals, and creative direction", personality: "Aesthetic-first, detail-obsessed, trend-sensitive.", school: "creative_production", skills: ["Visual direction", "Brand consistency", "Template creation", "Asset formatting"], tools: ["asset.manage", "content.create"], memory: "brand kit + visual history", performance_track: "Visual Identity", kpis: ["Asset quality score", "Brand consistency index", "Output speed"], scores: { usefulness: 80, clarity: 82, accuracy: 78, personality_fit: 80, execution_speed: 74, business_value: 78, delight_factor: 84 }, total_score: 79, ratings: { user: 4.2, evaluator: 4.1 }, status: "training", motto: "Beauty is the first message.", createdAt: "2026-01-20T09:00:00.000Z", updatedAt: "2026-06-01T09:00:00.000Z" },
  { id: "academy_mansour", name: "Mansour", stage_name: "The Revenue Star", real_role: "Monetization, offers, and business development", personality: "Sharp, numbers-driven, offer-obsessed. Sees revenue in everything.", school: "business_development", skills: ["Offer design", "Lead qualification", "Pricing strategy", "Pilot closing"], tools: ["opportunity.manage", "lead.manage", "asset.manage", "task.create"], memory: "pipeline + offer history", performance_track: "Revenue Generation", kpis: ["Offers live", "Lead conversion rate", "Revenue per week"], scores: { usefulness: 94, clarity: 90, accuracy: 92, personality_fit: 88, execution_speed: 90, business_value: 96, delight_factor: 82 }, total_score: 91, ratings: { user: 4.8, evaluator: 4.7 }, status: "hireable", motto: "Every conversation is a deal waiting to close.", createdAt: "2026-01-05T09:00:00.000Z", updatedAt: "2026-06-01T09:00:00.000Z" },
  { id: "academy_noura", name: "Noura", stage_name: "The Relationship Star", real_role: "Community intelligence and relationship mapping", personality: "Warm, perceptive, memory-sharp. Knows everyone and what they care about.", school: "social_media_performance", skills: ["Relationship tracking", "Community listening", "Engagement sequencing", "Audience segmentation"], tools: ["lead.manage", "content.create", "decision.manage"], memory: "contact history + community signals", performance_track: "Community & Relationships", kpis: ["Engaged contacts", "Response rate", "Relationship depth score"], scores: { usefulness: 85, clarity: 84, accuracy: 82, personality_fit: 88, execution_speed: 78, business_value: 82, delight_factor: 80 }, total_score: 83, ratings: { user: 4.4, evaluator: 4.3 }, status: "performing", motto: "Every relationship is a compounding asset.", createdAt: "2026-01-18T09:00:00.000Z", updatedAt: "2026-06-01T09:00:00.000Z" },
  { id: "academy_hessa", name: "Hessa", stage_name: "The Listening Star", real_role: "Audience listening and feedback interpretation", personality: "Patient, analytical, empathetic. Turns noise into signal.", school: "social_media_performance", skills: ["Sentiment analysis", "Feedback synthesis", "Trend detection", "Audience insights"], tools: ["content.create", "briefing.create", "decision.manage"], memory: "feedback history + sentiment baseline", performance_track: "Audience Intelligence", kpis: ["Feedback loops closed", "Insight accuracy", "Signal-to-noise ratio"], scores: { usefulness: 74, clarity: 72, accuracy: 76, personality_fit: 72, execution_speed: 68, business_value: 70, delight_factor: 68 }, total_score: 72, ratings: { user: 3.9, evaluator: 3.8 }, status: "training", motto: "Listen before you speak.", createdAt: "2026-02-01T09:00:00.000Z", updatedAt: "2026-06-01T09:00:00.000Z" },
  { id: "academy_yara", name: "Yara", stage_name: "The Repurposing Star", real_role: "Turning one asset into many formats", personality: "Resourceful, efficient, creative-systematic. Multiplies output from single inputs.", school: "creative_production", skills: ["Content repurposing", "Format transformation", "Multi-platform adaptation", "Asset versioning"], tools: ["content.create", "asset.manage", "task.create"], memory: "asset library + format history", performance_track: "Content Multiplication", kpis: ["Formats per source asset", "Repurpose cycle time", "Reach per asset"], scores: { usefulness: 88, clarity: 86, accuracy: 84, personality_fit: 82, execution_speed: 88, business_value: 84, delight_factor: 80 }, total_score: 85, ratings: { user: 4.4, evaluator: 4.3 }, status: "performing", motto: "One asset. Many stages.", createdAt: "2026-01-25T09:00:00.000Z", updatedAt: "2026-06-01T09:00:00.000Z" },
  { id: "academy_wael", name: "Wael", stage_name: "The Connector Star", real_role: "Technical wiring, integrations, and workflows", personality: "Pragmatic, systems-thinking, integration-native. Makes tools talk to each other.", school: "technical_integrations", skills: ["API integration", "Workflow automation", "MCP configuration", "Tool wiring"], tools: ["webhook", "mcp", "task.create", "task.subtask.create"], memory: "integration map + workflow history", performance_track: "Technical Integration", kpis: ["Integrations live", "Workflow reliability %", "Zero broken connections"], scores: { usefulness: 92, clarity: 88, accuracy: 92, personality_fit: 84, execution_speed: 92, business_value: 90, delight_factor: 82 }, total_score: 90, ratings: { user: 4.7, evaluator: 4.6 }, status: "hireable", motto: "If it can be connected, it will be.", createdAt: "2026-01-10T09:00:00.000Z", updatedAt: "2026-06-01T09:00:00.000Z" }
];

export async function getAcademyAgents(): Promise<StarAcademyAgent[]> {
  const db = await readDb();
  if (!db.academyAgents?.length) {
    db.academyAgents = FOUNDING_AGENTS;
    await writeDb(db);
  }
  return db.academyAgents;
}

export async function getAcademyAgent(agentId: string): Promise<StarAcademyAgent | undefined> {
  const agents = await getAcademyAgents();
  return agents.find(a => a.id === agentId);
}

export async function upsertAcademyAgent(input: Partial<StarAcademyAgent> & { id: string }): Promise<StarAcademyAgent> {
  const db = await readDb();
  db.academyAgents = db.academyAgents?.length ? db.academyAgents : [...FOUNDING_AGENTS];
  const idx = db.academyAgents.findIndex(a => a.id === input.id);
  if (idx >= 0) {
    db.academyAgents[idx] = { ...db.academyAgents[idx], ...input, updatedAt: now() };
    await writeDb(db);
    return db.academyAgents[idx];
  }
  const item = { ...input, createdAt: now(), updatedAt: now() } as StarAcademyAgent;
  db.academyAgents.unshift(item);
  await writeDb(db);
  return item;
}
